name: ng3
description: "A local music player app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  metadata_god: ^1.1.0
  file_picker: ^8.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_rust_bridge: 2.11.1
